### PR TITLE
support az:// urls

### PR DESCRIPTION
**Pull request by joschu**
This convention is supported by boostedblob.

### CODE REVIEW

**Comment by christopher-hesse** [comment]
Thanks! I was thinking this should be added.

**Comment by christopher-hesse** [comment]
I believe this means that things like `join()` will still return the `https://` form, is that fine or should the `az://` form be the standard?

**Comment by christopher-hesse** [comment]
I guess it would have to be a `configure()` option if we wanted `az://` to be the default because that could be a breaking change.

**Comment by joschu** [comment]
Yeah I don't have a strong opinion on this. I can't think of any situation where mapping to http:// would cause problems.

**Pull request merged**
