### PR TITLE
use a per-key token expiration

### PR DESCRIPTION
**Pull request by hauntsaninja**
Sharing expiration across multiple keys is only sound if we make sure to
use the minimum.

### CODE REVIEW

**Comment by christopher-hesse** [comment]
Whoops, good catch!  It looks like I added this bug long ago when token managers were made to handle multiple tokens: https://github.com/christopher-hesse/blobfile/blob/770bd80209f25eb31511a8c4175974ac9fb2252d/blobfile/blobfile.py#L52

**Comment by hauntsaninja** [comment]
Would it be possible to get a release for this?

**Comment by christopher-hesse** [comment]
https://github.com/christopher-hesse/blobfile/releases/tag/1.0.4

**Comment by hauntsaninja** [comment]
Thank you! :-)

**Pull request merged**
